---
- name: Play To Install Nginx Webserver On Ubuntu 20.04 Servers
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  vars:
   nginx_port: 80
   version: 1.0.0
  tags: nginx
  tasks:
  - name: Perform apt update
    shell: apt-get update -y
    tags: [apt, update]
  - name: Check Nginx Exists
    shell: nginx -v
    register: nginx_status_output
    ignore_errors: yes
    tags: [check] 
  - name: Install Nginx
    shell: apt-get install -y nginx && nginx -v
    when: nginx_status_output.rc != 0
    tags: [install] 
  - name: Start Nginx Server
    service: name=nginx state=started enabled=yes
    when: nginx_status_output.rc != 0
    tags: 
    - start

#ansible-playbook -i invfile Playbooks/1.nginx/1.simple-nginx.yml --tags basetools   
#ansible-playbook -i invfile Playbooks/1.nginx/1.simple-nginx.yml --tags basetools --limit testserver01
- name: Install Base Tools
  hosts: testserver01:testserver02:testserver03
  gather_facts: yes
  become: yes
  become_user: root
  tags: basetools
  tasks:
  - name: Perform apt update
    shell: apt-get update
  - name: Install Base Tools 1
    apt: name={{ item }} state=present
    with_items:
      - unzip
      - certbot
      - net-tools
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
  - name: Install Base Tools 2
    apt: name={{ item }} state=present
    with_items: [ jq, stress, tree ]
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
