---
- name: Check & Install AWS CLI
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: Check AWS CLI exists
    shell: aws --version
    register: aws_version_output
    ignore_errors: yes

  - name: Print Register Variable
    debug:
      msg: "{{ aws_version_output }}"

  - name: Print Return Code(rc)
    debug:
      msg: "{{ aws_version_output.rc }}"

  - name: Install Dependencies
    shell: apt update && apt install -y unzip net-tools jq stress
    when: aws_version_output.rc != 0

  - name: Install AWS CLI
    shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
    when: aws_version_output.rc != 0

  - name: Check AWS CLI exists Again
    shell: aws --version
    when: aws_version_output.rc != 0

  tags:
  - aws

- name: Check & Install Terraform
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  serial: 1
  vars:
    terraform_version: 1.9.5
  tasks:
  - name: Check Terraform Exists
    shell: terraform version
    register: terraform_status_output
    ignore_errors: yes

  - name: Install Terraform CLI
    shell: |
      rm -rf terraform.zip && rm -rf LICENSE.txt && rm -rf /usr/local/bin/terraform
      curl "https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip" -o "terraform.zip"
      unzip terraform.zip
      mv terraform /usr/local/bin
      terraform version
    when: terraform_status_output.rc != 0
    ignore_errors: yes
    
  - name: Check Terraform Version Again
    shell: terraform version

  tags:
  - terraform

